// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sKW_EIQGDQybLZWxm15UFOVnDAgO8kM',
    appId: '1:545211646727:web:cdca75014b1d39d295bba2',
    messagingSenderId: '545211646727',
    projectId: 'ebenezer-d570d',
    authDomain: 'ebenezer-d570d.firebaseapp.com',
    storageBucket: 'ebenezer-d570d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJ8JLKXKaUNU-VpTwr4oMuwcBZXRn3hk',
    appId: '1:545211646727:android:7cfad3fd23993ba495bba2',
    messagingSenderId: '545211646727',
    projectId: 'ebenezer-d570d',
    storageBucket: 'ebenezer-d570d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-XXzKw3ZfYlzGM4Y77tNmVq1Id3fkuE',
    appId: '1:545211646727:ios:0fcb660c2c7f1b1395bba2',
    messagingSenderId: '545211646727',
    projectId: 'ebenezer-d570d',
    storageBucket: 'ebenezer-d570d.appspot.com',
    iosClientId: '545211646727-amep8u21dl6i1vkifrqf7o3ch10k25j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );
}
